### ISSUE TITLE
Contributor knows who our target personas are and their motivations

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/convene#10]
In order to make good trade-offs that take into account our customer's needs and wants
As a Contributor
I want a small set of research-backed personas that represent who we are building Convene _for_ and their relative priority as we make design and implementation decisions

### This Issue May Be Closed When

- [x] The README references our 2~4 personas and links to our [Convene Persona's Document](https://docs.google.com/document/d/1JwTh2uFTc6pxsXu3njEVKQrv-J5HWExhd1rgT-ravt4/edit?usp=drive_web&ouid=109885491663234077023)
- [x] There is a link to the [Customer Development Research folder](https://drive.google.com/drive/folders/1gncYSkVIAj4CnlUZM9KPQlFdj_aqulDl) in the README

**Comment by zspencer** [comment]
I've updated this so that we store our Persona Research in a shared web-folder; instead of in Github, as that will be easier for @zinc-collective/designers to contribute to :).

**Comment by zspencer** [comment]
@user512 / @cjoulain  - Could one of you confirm for me that you can figure out the high-level of who we are building Convene for and what it is by starting  from the README while not logged into any Google accounts? Ideally by also confirming you can comment on any linked google docs?

Feel free to drop clarifying questions into any of the linked docs; as well as ask for whatever other things you need to understand what Convene is for.

**Comment by zspencer** [comment]
Got some feedback from [@Odd_Bloke@wrestle.town](https://wrestle.town/@Odd_Bloke/104252944125181683)

> not exactly what you're asking, but the Purpose section doesn't read very well in the mobile preview. If anything, because it's missing the concluding para, at a glance this appears to *be* an Open Core project: it's mentioned by name twice before any dissent to it is introduced.

**Comment by maximegalon5** [comment]
@user512 Do you feel that you have enough information on our G Drive to satisfy this issue? Would you like us to change the format of it in some way that is more useful to you?

**Comment by user512** [comment]
Looks good.
