### ISSUE TITLE
🥔🔌 `Utility`: `Stripe`

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/convene#1002]
- https://github.com/zinc-collective/convene/issues/252

Stripe is a powerful Payment Processor that allows Furniture developers to accept payments on the behalf of themselves or space members.

## Used in Gizmos:
- https://github.com/zinc-collective/convene/issues/831

**Comment by rosschapman** [comment]
🧹  Relegated to [cold storage](https://docs.google.com/spreadsheets/d/1Z_pC21sAKAMyB7xiRAY1--bm1ZKEuFzCzSXfqzHaF08/edit?gid=1828229424#gid=1828229424).
