### ISSUE TITLE
🥔👩‍🎤 `Operators`

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/convene#103]
- https://github.com/zinc-collective/convene/issues/103 help a https://github.com/zinc-collective/convene/issues/892 run smoothly and handle the day-to-day moderation of https://github.com/zinc-collective/convene/issues/1154 and People.

## Use Cases

- https://github.com/zinc-collective/convene/issues/890
- 🥔 `Operator`s have broad permissions on `Furniture`, `Space`, `Room`, `Invitation`, `Membership`
- 🥔 `Operator` API access

## Bugs

- [x] https://github.com/zinc-collective/convene/issues/1659

**Comment by user512** [comment]
# TODO fixes:
## Room create/ update:
1. Person name needs to be shown.
1. Room name needs to be shown.
1. Room ownership isn't human readable.
1. Room Publicity should be a drop down.
1. Room access level should be a dropdown.

We should create a guide to create/ update workspace, create/ update room guide for operator to do this easily. Now the operator has to understand the models to operate.

**Comment by colombene** [comment]
Room setup was wireframed here and is separate from workspace setup. Are there specific changes you need on this? https://xd.adobe.com/view/fd425dbe-5384-44c9-997a-eeee6e886a86-a811/screen/847810bf-5d62-4131-a70d-d9efdfadb334/

**Comment by zspencer** [comment]
Thanks @user512! I've moved your TODO list to under neath the "Rough Edges" checkbox, so folks who want to take a swing at this don't need to go through the application.

@colombene  - This may not want wireframing, as it's essentially an "Admin panel" for the underlying data models that is auto-generated. The "Operators"  persona is what I'm using to glom together the folks who are running the Convene service (either as Account Managers, Customer Support, Support Engineers, or Site Resilience Engineers). 

That said, if you want to build wireframes for that "section" of the application; feel free to do so!

**Comment by rosschapman** [comment]
🧹  Relegated to [cold storage](https://docs.google.com/spreadsheets/d/1Z_pC21sAKAMyB7xiRAY1--bm1ZKEuFzCzSXfqzHaF08/edit?gid=1828229424#gid=1828229424).
