### ISSUE TITLE
Convene's CPU usage.

### ISSUE THREAD

**Issue by cjoulain** [zinc-collective/convene#107]
Was interested in how Convene rated with competitors in terms of CPU. Mostly curious about client-side performance but server-side performance might also be good to get metrics on.

Thought of question because I know some folks tend to prefer tools just based on whether it not it slows down their machine significantly, esp. if they have older computers.

@zspencer responded with this and wanted to document here: 

<blockquote>

I expect that a first pass of a “Performance” feature would have one branch in infrastructure/features/performance.feature for the Operators managing a Convene instance, so they know the Mb/sec/participant  + the CPU usage; so they can plan out their videobridge deployment and another branch in the top-level features/in-browser-performance.feature 

For now, getting “Self-reported” data is probably all we can do for in-browser performance. We could maybe add a way to report performance issues or notice them on the client and gather some system information? Alternatively, we could ask some folks who have crappy devices to use Convene and monitor their system performance to get some initial data.

</blockquote>

**Comment by user512** [comment]
Interesting finding from Jitsi community on high client side cpu usage.
https://community.jitsi.org/t/host-a-meeting-with-500-people-ideas/34672/4
Gist of it is when someone talk, the UI updated and with many users, the client update too frequently and cause CPU usage spike.

**Comment by zspencer** [comment]
Nice find @user512, There’s also this thread - https://community.jitsi.org/t/high-cpu-utilization-on-client-end/25764/25

I’m also not opposed to looking into [BigBlueButton](https://docs.bigbluebutton.org/) for providing our underlying audio/videobridge if we keep running into jitsi performance issues.

**Comment by zspencer** [comment]
GitHub _Really_ needs to move the “Close and Comment” button to far side of the panel...

**Comment by zspencer** [comment]
@cjoulain - If you feel like you're satisfied with our response, would you be willing to close this ticket? I'm also happy to create a ticket with actionable next steps.

**Comment by cjoulain** [comment]
@zspencer Closing this ticket. Feel free to create a new one with actionable next steps. Not sure what work to monitor performance would look like for Convene.
