### ISSUE TITLE
Accepting a space invitation causes a 500

### ISSUE THREAD

**Issue by anaulin** [zinc-collective/convene#1078]
I went through the flow to accept a Space invitation into the demo Marketplace space, and once I entered my one-time code it threw an error:

![image](https://user-images.githubusercontent.com/6729309/215611130-6187e79c-bb18-4f96-be51-3bd885f8b564.png)

For debugging reference, the invitation was for ana@zinc.coop, invitation URL https://convene.zinc.coop/spaces/piikup-marketplace/invitations/eba2e5d2-5024-4d23-b3c6-26d3a8311d78/rsvp

**Comment by zspencer** [comment]
Found it in Sentry, seems to be an intersection between [Space: Memberships](https://github.com/zinc-collective/convene/issues/117) and [BYO Domains](https://github.com/zinc-collective/convene/issues/74)
