### ISSUE TITLE
🌫️⛰️ `Neighborhood`: Provisioning an in-building `Pod`

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/convene#1089]
It would be amazing if we could design the infrastructure to support an in-home or in-office "pod" that serves as a hyper-local cache/distributed point-of-contact for a sub-set of the Spaces hosted in a given Neighborhood.

I could imagine a universe where Pods are home-buildable (or for purchase as pre-assembled from local computing cooperatives) with different configurations (Media Server with big disk energy, tiny form-factor with speakers and voice activation for home assistants, eInk displays for your kitchen shopping list/calendar/recipe reference, etc.).

Ideally, anyone with a spare computer (x86 or arm64) could install a base image onto their hardware (or a VM); authenticate it with their Neighborhood; and  grant their Neighbors to the right to leverage their Pod as a high, medium, or low-trust cache for their Space data.

## Watering Hole
> t's not easy to self-host a Mastodon instance, but hot take: it should be. Many of us have large amounts of computation and storage laying about (partly a consequence of single-purpose devices, detritus of the war on general purpose computing), but no effective way of putting it to use.
> 
> So far, I really only see one company trying to make it easier for amateur users to self-host stuff: Synology. https://social.coop/@cgranade@mathstodon.xyz/109764621157182558

> Big instances are problematic.
> 
> That the goto solution to the DDoS attack is "throw more Cloud at it" is problematic.
> 
> How are small instance operators supposed to guard themselves? Add yet another Cloud rental fee?
> 
> Why do we even care if mastodon.social goes down? Oh, because we (meaning he) let it get too big already.
> 
> Why isn't a collectively run CDN built into the substrate of the fediverse so that we never need a Cloudflare or Fastly or any other Big Tech feudal lord? - https://union.place/@toolbear/109790747140648985

**Comment by rosschapman** [comment]
🧹  Relegated to [cold storage](https://docs.google.com/spreadsheets/d/1Z_pC21sAKAMyB7xiRAY1--bm1ZKEuFzCzSXfqzHaF08/edit?gid=1828229424#gid=1828229424).
