### ISSUE TITLE
🌫️🗜️✨ `Gizmo`: `Wisdom Garden`

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/convene#1094]
Organizing what we know, keeping it well, tidying it from the weeds of reality drift, and stewarding it to make the wisdom we've gathered discoverable, browsable, and accessible is one of the hardest problems of the digital age.

A Wisdom Garden allows a group to collaboratively steward information

Supplants: Notion, Google Drive, MediaWiki, Dropbox Paper, etc.

### Roles
_Note, I would expect people could hold any of these Roles_
- Editor (✍️) - Accepts or Reverts changes to the Garden
- Contributor (📇) - Suggests changes to the Garden
- Reader (📚) - Browses, reads, and appreciates the content of the garden

### Use Cases
- 🌫️ Planting a Seed of Wisdom
- 🌫️ Tending Wisdom
  - 🌫️ Contributor suggests changes
  - 🌫️ Editor responds to suggestions 
  - 🌫️ Editor accepts change suggestion
- 🌫️ Searching for Wisdom
- 🌫️ Browsing Wisdom
  - 🌫️ Following a trail of Wisdom
  - 🌫️ Reacting to a chunk of Wisdom
- 🌫️ Disambiguating between overloaded terms

#### Legend
- 🌫️- We're not ready to nurture this use case...
- 🌱- We're nurturing this use case, but it's not quite ready yet

**Comment by rosschapman** [comment]
🧹  Relegated to [cold storage](https://docs.google.com/spreadsheets/d/1Z_pC21sAKAMyB7xiRAY1--bm1ZKEuFzCzSXfqzHaF08/edit?gid=1828229424#gid=1828229424).
