### ISSUE TITLE
🗺️ `Marketplace`: `DeliveryArea`

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/convene#1136]
- https://github.com/zinc-collective/convene/issues/831
- https://github.com/zinc-collective/convene/issues/1325

In the beginning, the [Marketplace](https://github.com/zinc-collective/convene/issues/831) only supported per-Marketplace delivery pricing. 

When chatting with [Piikup](https://github.com/zinc-collective/convene/issues/832), we learned that they prefer to price  on a per-`Marketplace` basis based on which `DeliveryArea` the `Shopper` collects

### Fauxsonas
See [Marketplace Fauxsonas](https://github.com/zinc-collective/convene/issues/831)

### Use Cases

- [x] 🥔 `Distributor` adds `DeliveryArea`s
- [ ] #2014
- [x] 🥔 `Shopper` sets `DeliveryArea` for `Order`
- [x] 🥔`Shopper` pays `DeliveryFee` based upon `DeliveryArea`
- [x] 🥔 `Distributor` sets `OrderBy` and `DeliveryWindow` for `DeliveryArea`
- [x] 🥔`Shopper` sees `DeliveryConstraints` based upon `DeliveryArea`
- [x] 🥔 `Shopper` may not see `Marketplaces` without a `DeliveryArea`

**Comment by zspencer** [comment]
From April:
> We're going for Catering, so Restaurants and Food Makers and the pricing is based on City.
> So if we are delivering from Cafe Gabriele or Understory those are Catering orders, and the prices are:
> - Oakland, Alameda, Berkeley and Emeryville is $50 for those cities
> - San Francisco, $75

**Comment by zspencer** [comment]
I think this is good enough for us to close! We can keep refactoring and tidying if we want, but I'm not sure what other use cases it's missing.

**Comment by zspencer** [comment]
Re-opening because it does seem like we have more work to do to make this tight.

**Comment by rosschapman** [comment]
🧹  Relegated to [cold storage](https://docs.google.com/spreadsheets/d/1Z_pC21sAKAMyB7xiRAY1--bm1ZKEuFzCzSXfqzHaF08/edit?gid=1828229424#gid=1828229424).
