### ISSUE TITLE
🥔✨ `Marketplace`: `Tax` Collection and Compliance

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/convene#1137]
- https://github.com/zinc-collective/convene/issues/831
- https://github.com/zinc-collective/convene/issues/1324
- https://github.com/zinc-collective/convene/issues/1326

## Use Cases

- [x] 🥔 `Seller` sets `TaxRate`s
  - [x] 🥔 As a %age of `Product#price`
  - [ ] 🌱 As a fixed amount per unit
  - [x] 🥔 `TaxRate`s are shared across a `Space`s `Marketplace`s
 - [x] 🥔 `Seller` associates `TaxRate`s to `Product`s 
- [x] #1469
- [x] 🥔 `Shopper` pays `Taxes`
- [x] #1655

**Comment by zspencer** [comment]
I got a chance to speak with Adrionna Fike, the Board member at NoBAWC  who worked at Mandela up until last year. The lowdown was:

1. There are city and state level sales taxes
2. Most sales taxes are collected from the customer, but *some* sales taxes are collected in part from the customer *and* the seller (i.e. the sugary foods tax)
3. Some products may be covered under multiple sales-taxes (i.e. bottled beverages > 16oz have a tax *and* a deposit fee)

For now, we'll likely want to allow a Space to define the `SalesTax` they collect across all `Marketplaces`, for example:

- Sales Tax (City of Oakland): 6%
- Bottle Deposit (State of California): $0.10
- Tobacco Tax (State of California): 13%

And each `Product` can then be associated to multiple taxes on the `Marketplace::ProductsController#edit`

**Comment by zspencer** [comment]
Do we want to group the taxes with the products when showing them? Or show them on a per-tax-rate basis? Right now we do:

```
Product A
Product B
Taxes Total
Delivery Fee
Total
```

but maybe it would make sense to organize it like:

```
Product A
  (Product A Tax)
Product B
Product C
  (Product C Tax)
Sub Total
Delivery Fee
Taxes 
Total
```

or

```
Product A
Product B
Product C
Product Total

Tax Rate A
Tax Rate B
Tax Rate Total

Delivery Fee

Total
```

**Comment by rosschapman** [comment]
🧹  Relegated to [cold storage](https://docs.google.com/spreadsheets/d/1Z_pC21sAKAMyB7xiRAY1--bm1ZKEuFzCzSXfqzHaF08/edit?gid=1828229424#gid=1828229424).
