### ISSUE TITLE
🌫️`Gizmo`: `Usher`

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/convene#1151]
In order to simplify `Room`s, I'd like us to get rid of the `locked` / `internal` etc. distinctions and instead leverage a piece of Furniture. 

## Fauxsonas

- Guest - Unauthenticated `Person`
- ??? - Authenticated `Person` who is not a `Member` of any `Space` int he `Neighborhood` (Perhaps this is `Guest` and `Visitor` is someone we know nothing about?
- Neighbor - Authenticated `Person` who is a `Member` of any `Space` in the `Neighborhood`
- Member - Authenticated `Person` who is a `Member` of this `Space`

## Use Cases

- [ ] Adding `Bouncer` to `Room`
- [ ] `Bouncer` prevents access to `Room`
  - [ ] By redirecting to a different `Room` when the `Room` is being opened by someone who is less than a...
    - [ ] A `Visitor`
    - [ ] A `Guest`
    - [ ] A `Neighbor`
    - [ ] A `Member`
    - [ ] A `Member` of a particular `Group`  - https://github.com/zinc-collective/convene/issues/811
  - [ ] By requiring an `Access Secret`

**Comment by anaulin** [comment]
Quibble: a name that feels kinder than "bouncer" would be nice. Some ideas: usher, doorbot, doorkeeper, roomkeeper

**Comment by zspencer** [comment]
I like Usher!

**Comment by rosschapman** [comment]
🧹  Relegated to [cold storage](https://docs.google.com/spreadsheets/d/1Z_pC21sAKAMyB7xiRAY1--bm1ZKEuFzCzSXfqzHaF08/edit?gid=1828229424#gid=1828229424).
