### ISSUE TITLE
`Neighborhood`: Enforce style guide in CI

### ISSUE THREAD

**Issue by KellyAH** [zinc-collective/convene#1156]
1.  use husky or rubocop standard against files that changed.
`bin/rubocop -a $(git diff main --name-only --diff-filter=d | grep '\.rb')`

^^^^ Runs rubocop only against the changed files (and none that were deleted) 

3.  and re generate the erd via `bin/erd`
as a pre-push or pre-commit.

- [x] `standard` for `rb` files https://github.com/zinc-collective/convene/pull/1184
- [x] `prettier` for `css` and `js` https://github.com/zinc-collective/convene/pull/1184

**Comment by zspencer** [comment]
Well, `husky` would be for if we wanted to make it so we would run pre-commit. I think it's fair to just run `rubocop` in ci and not do a pre-commit.

**Comment by anaulin** [comment]
The ERD checks feel more appropriate for a pre-commit (it requires having a database setup, installing graphviz, etc). We could also add a pre-commit to do autoformatting. If folks are interested in that, it would be a different issue.

Personally I'm neutral on pre-commits. They add yet another setup step for new developers, but they can be helpful. 🤷🏼‍♀️
