### ISSUE TITLE
`Neighborhood`: Run `brakeman` on PRs

### ISSUE THREAD

**Issue by KellyAH** [zinc-collective/convene#1157]
try running [brakeman](https://rubygems.org/gems/brakeman/versions/5.0.4) on PRs to catch changes that are security issues.

**Comment by zspencer** [comment]
Good call!

**Comment by anaulin** [comment]
Will this give us anything more in addition to what we get from Dependabot? I feel like Dependabot is marginally better because it keeps itself up-to-date with the latest CVEs, while Brakeman is a gem that we would have to always keep updating to make sure not to miss anything.

**Comment by zspencer** [comment]
The difference between the two is that `brakeman` provides static analysis, whereas `dependabot` bumps packages.

**Comment by anaulin** [comment]
The security side of Dependabot also performs static analysis and sends security alerts.

The only difference I see with Brakeman is that Brakeman can do it on not-checked-in code, while Dependabot only runs on code that's already in the repo.

Here is an example Dependabot security alert for Convene from 3 days ago:
![Screenshot_20230305_152143_Gmail.jpg](https://user-images.githubusercontent.com/6729309/222991824-f5ce24ef-f182-4600-9e5c-4bd0a678d492.jpg)

**Comment by anaulin** [comment]
The security side of Dependabot also performs static analysis and sends security alerts.

The only difference I see with Brakeman is that Brakeman can do it on not-checked-in code, while Dependabot only runs on code that's already in the repo.

Here is an example Dependabot security alert for Convene from 3 days ago:
![Screenshot_20230305_152143_Gmail.jpg](https://user-images.githubusercontent.com/6729309/222991824-f5ce24ef-f182-4600-9e5c-4bd0a678d492.jpg)

Oh, and Dependabot looks at JavaScript and Ruby issues, while Brakeman I think is Ruby-only.

**Comment by zspencer** [comment]
Gotcha, so you're suggesting we use the GitHub Code Scanning feature (which uses something called `CodeQL` under the covers? https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning) as opposed to `brakeman`. I don't have a preference either way.

**Comment by anaulin** [comment]
@KellyAH would continuing to rely on Dependabot's security alerts satisfy your goals with this ticket?

**Comment by rosschapman** [comment]
🧹  Relegated to [cold storage](https://docs.google.com/spreadsheets/d/1Z_pC21sAKAMyB7xiRAY1--bm1ZKEuFzCzSXfqzHaF08/edit?gid=1828229424#gid=1828229424).
