### ISSUE TITLE
🛠️ `Neighborhood`: Keep track of code coverage as we review and merge code

### ISSUE THREAD

**Issue by anaulin** [zinc-collective/convene#1198]
- https://github.com/zinc-collective/convene/issues/892

As Convene becomes a More Serious Product, it would be nice to have some automated tooling to help us keep our testing up-to-date.

Some options:
* add SimpleCov and use the SimpleCov+ GitHub Action (https://github.com/marketplace/actions/simplecov-action), to check for a minimum code coverage on PRs
* integrate a 3rd party service like https://codecov.io/ or https://codeclimate.com/ (both these examples are free for open source projects)

Thoughts?

**Comment by zspencer** [comment]
I think this is something that would be super exciting! I would love to combine it with a piece of furniture that kept the history, rather than requiring us to use an outside service.

**Comment by jalcine** [comment]
[https://github.com/Librecov/librecov](https://github.com/Librecov/librecov) could be an option for furniture. It does look a _little unmaintained_ , assuming from [https://github.com/Librecov/librecov/issues/203](https://github.com/Librecov/librecov/issues/203). I have experience with Elixir projects, so I can try seeing if I can integrate this into Convene over the next week.

If not, this does feel like a (big) project in itself that the general developer community interested in self-hosting would be interested in seeing a solution for.

(Originally published at: https://jacky.wtf/2023/3/HhHK)

**Comment by zspencer** [comment]
Yea, I could see us offering a [Hosted Utility](https://github.com/zinc-collective/convene/issues/891) for `LibreCov` , but that seems a lot heavier weight than a tiny piece of Furniture that:

1. Listens for a PUT of `SimpleCov` results 
2. Parses those for high level metrics (i.e. x Lines of Implementation Code, y % covered by z lines of Test Code)

If we were to go with a Hosted Utility, I'd like to have a few answers to questions like:

- Is the Librecov Hosted Utility a Neighborhood resource? Or Space? If Space, do we require it to be ran on a VM provider maintained by the Space Owner? If Neighborhod, is a librecov installation sufficiently useful  to re-inflate our "Backend" VM?
- How do we make sure our Neighborhood-level Librecov installation stays well-patched and doesn't serve as an entrance point for a security vulnerability which could leak Space-owners IP?
- If it's a Space-level installation, what are the hosting costs on a per-month basis for the Space? At present, we are shooting for ~100% markup over server costs; so if it's $5/mo in compute to run a secure LibreCov install, we'll need to charge $10/mo per Space with a LibreCov add-on installed.

I think a project like [`abra` by CoopCloud](https://recipes.coopcloud.tech) is well suited for holding the code for provisioning and updating a LibreCov deployment.

**Comment by rosschapman** [comment]
🧹  Relegated to [cold storage](https://docs.google.com/spreadsheets/d/1Z_pC21sAKAMyB7xiRAY1--bm1ZKEuFzCzSXfqzHaF08/edit?gid=1828229424#gid=1828229424).
