### ISSUE TITLE
🌫️ `Neighborhood`: Provisioning a `Neighborhood`

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/convene#1449]
- https://github.com/zinc-collective/convene/issues/892

Convene Neighborhoods can run on low-cost PaaS, like [Heroku](https://www.heroku.com/home) or [Render](https://render.com/); on Virtual Machines provided by [AWS](https://aws.amazon.com/), [DigitalOcean](https://www.digitalocean.com/), [Linode](https://www.linode.com/), or [Vultr](https://www.vultr.com/).

Ideally, a Convene Neighborhood with one or two low-traffic spaces would cost ~$5/mo. Higher-compute/bandwidth [Neighborhood Hosted Utilities](https://github.com/zinc-collective/convene/issues/891) would drive costs up.

## Use Cases

- [ ] On Heroku
  - [ ] Using Git
  - [x] [Using GitHub](https://github.com/zinc-collective/convene/blob/main/docs/deployment.md#GitHub)
  - [ ] Using Images
- [ ] On Ubuntu 22.04
  - [ ] Using Abra
  - [ ] Manually?
- [ ] On Render
- [ ] On Kubernetes
- [ ] On Docker Swarm?
- [x] https://github.com/zinc-collective/convene/issues/1089

**Comment by zspencer** [comment]
@daltonrpruitt - For Heroku, we should be able to start out encourage people to fork and then follow  [the guide to deploying a Rails app to heroku](https://devcenter.heroku.com/articles/getting-started-with-rails7#deploy-the-application-to-heroku). We may also want to read/encourage operators to read the [guide to using GIT](https://devcenter.heroku.com/categories/deploying-with-git)

We can work towards a Docker Image for Heroku after that; especially since that will help us get standard Kubernetes/Docker Swarm

**Comment by rosschapman** [comment]
🧹  Relegated to [cold storage](https://docs.google.com/spreadsheets/d/1Z_pC21sAKAMyB7xiRAY1--bm1ZKEuFzCzSXfqzHaF08/edit?gid=1828229424#gid=1828229424).
