### ISSUE TITLE
🌸✨ `Members`: `Invitation` email should convey which `Space` and `Person` it came from

### ISSUE THREAD

**Issue by anaulin** [zinc-collective/convene#1481]
- https://github.com/zinc-collective/convene/issues/1514

The current Space invitation email doesn't have much info about who / what is actually inviting you and to what, unless you already know what Convene is:

![image](https://github.com/zinc-collective/convene/assets/6729309/6483d058-7abd-471b-8a55-58cfc0af90a8)
![image](https://github.com/zinc-collective/convene/assets/6729309/ecafe8f6-fcf5-4c70-84e2-211956149a06)

It would be good to:
- [x] add the Space name to the subject line (e.g. "You are invited to SPACE NAME", instead of "Invitation email") https://github.com/zinc-collective/convene/pull/1483
- [x] add the name of the invitor to either the subject line (e.g. "PERSON NAME invites you  SPACE NAME") or the "from" text (e.g. "Convene Support on behalf of PERSON NAME")

**Comment by anaulin** [comment]
@KellyAH assigning this to you in case you are looking for something to do, but don't feel obliged to do it!

**Comment by KellyAH** [comment]
Ooo exciting! I've never worked with the Rails Mailer templates before. Thanks so much! I'll give it a shot today and this weekend!

**Comment by anaulin** [comment]
@KellyAH thank you! Don't hesitate to send questions if you get stuck.

And in case you aren't aware of this feature: Rails mailer previews can be very helpful, see https://guides.rubyonrails.org/action_mailer_basics.html#previewing-emails

**Comment by zspencer** [comment]
Great catch! I've linked the card to the "nearest-upstream-leaf" in the product garden wiki thing. We probably should split `Invitations` into it's own high level issue since `Members` is getting pretty overloaded; but I will do that "someday when I think about it."

**Comment by zspencer** [comment]
> Sentry issue: [CONVENE-1H](https://zinc-collective.sentry.io/issues/4210828106/?referrer=github_integration)

Whoops! Apparently sending an email with a `from` field missing an actual *email address* does not uhhh.... work...

We'll probably want to:

- [ ] Fix the bug
- [ ] Investigate adjusting `maildev` to angrily reject malformed emails
- [ ] Included the email address set in the `EMAIL_DEFAULT_FROM` variable.
