### ISSUE TITLE
🌱✨ Setting the `Space` Domain

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/convene#1513]
- https://github.com/zinc-collective/convene/issues/74

In [Space] -> [Edit] -> [Website Settings], `Members` may specify the `Domain` name their `Space` is reachable at on the public web.

## Use Cases
- [x] Show the `Space`'s `Domain` https://github.com/zinc-collective/convene/pull/1600
- [x] Setting the `Space` Domain Name https://github.com/zinc-collective/convene/pull/1595
- [ ] Enforcing Access through the `Domain`

**Comment by zspencer** [comment]
@KellyAH - This may be a good one to tackle soon; it's already a bit work-in-progress; in that Operators can set `Space#branded_domain` via the rails console; however it would be better if:

- Any `Space` `Member` could set the domain via the UI 
- We could toggle whether accessing the `Space` must be through the `Domain` or not.

When you're ready, I can give you a few places to look and a better breakdown of the technical next steps; or (as always) feel free to explore on your own if that suits your training style better.

**Comment by KellyAH** [comment]
I will start working on this tomorrow during our wed session. 6/21

**Comment by anaulin** [comment]
It would be nice to start by at least _showing_ the branded domain for the Space in the configuration screen (if there is a branded domain).

**Comment by rosschapman** [comment]
🧹  Relegated last task to [cold storage](https://docs.google.com/spreadsheets/d/1Z_pC21sAKAMyB7xiRAY1--bm1ZKEuFzCzSXfqzHaF08/edit?gid=1828229424#gid=1828229424).
