### ISSUE TITLE
🌫️ `Member`: Profiles

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/convene#153]
- https://github.com/zinc-collective/convene/issues/117
- https://github.com/zinc-collective/convene/issues/118

People have different ways of representing themselves, and the way they represent themselves in one Space may not be how they want to represent themselves in other Spaces.

## Use Cases
- [x] Create, Update and Remove a `Member` `Profile` (https://github.com/zinc-collective/convene/issues/165)
- [ ] `Person` has a default `Profile`
- [ ] `Member` sets `Profile` for `Space`

**Comment by zspencer** [comment]
@colombene / @anaulin - Does this feel like it synthesizes the different pathways someone may take to enter a room through the Entry Hall?  


(Note: The "Scenario Outline" feature is a way to replace the bit of the step in the `<Actor>` brackets with the value; so that we can run the same test against a number of different user-types. Not sure if we will wind up using it in the actual test side of things. Thoughts @KellyAH / @user512 / @eg-bet / @cjoulain?)

**Comment by user512** [comment]
I think both pathways and the feature outline makes sense.

**Comment by anaulin** [comment]
> customized Identity is the default when they begin to Enter other Rooms in the Space

I had assumed that a person's last used Customized Identity would be the default when they begin to Enter other Rooms in _any_ Convene Space. Or do we want to have a per-Space default? (Seems easier to have one default to begin with, but I see the value in having a per-Space default.)

**Comment by anaulin** [comment]
But yes, I think this makes sense and clarifies (for me) what our planned user flows are.

**Comment by zspencer** [comment]
If it's not too much of a burden, I'd appreciate if our implementation respected that someone's identity is contextual to the space they are within; so that people who do have to present differently in different contexts aren't asked to carry the cost of making that decision each time they enter a space.

That said, I'm OK with us getting there incrementally.

**Comment by rosschapman** [comment]
🧹  Relegated to [cold storage](https://docs.google.com/spreadsheets/d/1Z_pC21sAKAMyB7xiRAY1--bm1ZKEuFzCzSXfqzHaF08/edit?gid=1828229424#gid=1828229424).
