### ISSUE TITLE
🌸✨ `Journal`: The "Add Journal Entry" link takes a long time to scroll to

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/convene#1567]
- https://github.com/zinc-collective/convene/issues/1566

When signed in on https://beta.zeespencer.com, I noticed that the "Add Journal Entry" link takes a while to scroll to. Maybe we add one to the top as well? Or do something else to make it  a bit easier to access?

**Comment by zspencer** [comment]
@KellyAH or @daltonrpruitt - Is this something either of you want to tackle? If so, just assign yourself to it! Otherwise I will maybe pick it up when I want to build something that is "Not Actually Important, But Still Kinda Meaningful (At Least To Me)"

**Comment by KellyAH** [comment]
Adding a "Add Journal Entry" button to the top of the page sounds good. I'll give it a try.

**Comment by KellyAH** [comment]
I will start this tomorrow 6/20. I need to update my resume w/ rails work.

**Comment by zspencer** [comment]
Thank you! This is much nicer!
