### ISSUE TITLE
🐛 `Invitations` and `People`: whitespace in email addresses gets saved to the database, preventing us from identifying `Members`

### ISSUE THREAD

**Issue by anaulin** [zinc-collective/convene#1607]
- https://github.com/zinc-collective/convene/issues/1514
- https://github.com/zinc-collective/convene/issues/117

We have run into a bug where someone gets invited to an email address with spaces, e.g. `'alex@example.com '`, and they get the invitation email and can accept the invitation and so on, but in the system we end up with a Person with the email address `'alex@example.com '`, which does not match `'alex@example.com'` when the log into Convene.

We should strip leading and trailing whitespace in the email field for Invitations and Persons. This could be done with some callbacks, or adding the `strip_attributes` gem (https://github.com/rmm5t/strip_attributes) and applying it to these fields.

**Comment by zspencer** [comment]
Thanks @anaulin !I think the `strip_attributes` gem is a reasonable addition, weighing in at  a gentle ~87 loc plus it has [custom matchers](https://github.com/rmm5t/strip_attributes/blob/master/lib/strip_attributes/matchers.rb#L6-L11)!

**Comment by zspencer** [comment]
@zinc-collective/convene-contributors Anyone interested in trying to tackle this? The way I would tackle it would be:

1. Add the `strip_attributes` gem
2. Add [some expectations](https://github.com/rmm5t/strip_attributes/blob/master/lib/strip_attributes/matchers.rb#L6-L11) to the `spec/models/invitation_spec` and `spec/models/person_spec.rb`  to confirm it strips the `contact_location` and `email`
3. Use [`strip_attributes only: [...]` ](https://github.com/rmm5t/strip_attributes/tree/master#using-only)to trim the fields on the `Person` and `Invitation` model
