### ISSUE TITLE
🐞 `Marketplace`: order history for Marketplace managers contains incomplete orders

### ISSUE THREAD

**Issue by anaulin** [zinc-collective/convene#1691]
I noticed in the production Piikup marketplace that the Order History is showing every single shopping cart that was ever created for that Marketplace:
![image](https://github.com/zinc-collective/convene/assets/6729309/a55dc94a-fd5a-4d8e-95e0-4e7dc3ba2bdd)

I think this Order History page for the Marketplace should only show orders that were completed (paid). (Maybe one day we want to show "abandoned orders" somewhere else, but that would be a separate view.)

**Comment by zspencer** [comment]
Yikes; would you prefer we fix this by:

- Filtering off of current data
- Remucking the domain model so that an `Order` and a `Cart` are separate
- Using Rails built-in Polymorphism to make sure `Order` and `Cart` are queried indepenetly?

**Comment by anaulin** [comment]
I think an immediate fix to show only "paid" orders is a good idea.

Mid/long-term we might re-think the domain model, but we shouldn't block fixing this bug on that re-think.

**Comment by zspencer** [comment]
Alright, I'll do a quick fix for filtering by paid!

**Comment by zspencer** [comment]
Bam: https://github.com/zinc-collective/convene/pull/1703
