### ISSUE TITLE
🐛 `Marketplace`: "Content missing" displays when click "Add Stripe Account"

### ISSUE THREAD

**Issue by KellyAH** [zinc-collective/convene#1806]
- https://github.com/zinc-collective/convene/issues/1622

# problem
Given a section exists w/ a fresh marketplace gizmo (missing a Stripe Account/API key)

1. Go to "Manage Marketplace" e.g prod sandbox: https://convene.zinc.coop/spaces/sandbox/rooms/fake-shop/marketplaces/fac9f78c-23bd-423a-bf5a-4fc7a74a9685/edit

![Screenshot 2023-09-06 at 6 10 18 PM](https://github.com/zinc-collective/convene/assets/16140873/c098b343-8f95-4c34-bfde-8b3127bfc403)

3. click "Add Stripe Account" link

**expected behavior**
See page to Add Stripe Account
https://convene.zinc.coop/spaces/sandbox/rooms/fake-shop/marketplaces/fac9f78c-23bd-423a-bf5a-4fc7a74a9685/stripe_account
![Screenshot 2023-09-06 at 6 32 16 PM](https://github.com/zinc-collective/convene/assets/16140873/4bc073dc-6f4f-4e48-b842-f4d8ad068580)

**actual behavior**
See  "Content missing" display on the page
![Screenshot 2023-09-06 at 6 10 24 PM](https://github.com/zinc-collective/convene/assets/16140873/ad5af0d5-be0b-4a86-8166-f66b13dd3a96)

Replicated beak on local and prod sandbox.

**Comment by anaulin** [comment]
See associated error reported by Sentry here: https://github.com/zinc-collective/convene/issues/1807

**Comment by zspencer** [comment]
Thank you Kelly and Ana!

**Comment by zspencer** [comment]
Gonna tackle this next!

**Comment by zspencer** [comment]
Patch is in! Turns out there were a number of sad things happening here. Once I get code review; I'll merge and deploy and assign to @KellyAH for testing!

**Comment by zspencer** [comment]
This has been fixed and merged; the deploy should be complete by 6:45 PT on 9/20; at which point if you could re-test it for me @KellyAH and close the issue / provide feedback I would be stoked!

**Comment by KellyAH** [comment]
✅ confirmed fixed on prod.  

Tested on https://sandbox.zinc.coop/spaces/sandbox/rooms/fake-shop/marketplaces/fac9f78c-23bd-423a-bf5a-4fc7a74a9685/edit
