### ISSUE TITLE
🐛 `Marketplace`: payment_settings page fails to load

### ISSUE THREAD

**Issue by KellyAH** [zinc-collective/convene#1810]
- https://github.com/zinc-collective/convene/issues/1576

# problem
Given a section exists w/ a fresh marketplace gizmo (missing a Stripe Account/API key)

1. Go to "Manage Marketplace" e.g prod sandbox: https://convene.zinc.coop/spaces/sandbox/rooms/fake-shop/marketplaces/fac9f78c-23bd-423a-bf5a-4fc7a74a9685/edit

![Screenshot 2023-09-06 at 6 10 18 PM](https://github.com/zinc-collective/convene/assets/16140873/c098b343-8f95-4c34-bfde-8b3127bfc403)

3. click "payment settings" button

**expected behavior**
payment settings loads

**actual behavior**
404
![Screenshot 2023-09-06 at 6 56 14 PM](https://github.com/zinc-collective/convene/assets/16140873/402ae471-aed2-4ea0-8d60-e409f74332b4)

Replicated beak on local and prod sandbox.

Preview for component is also broken
http://127.0.0.1:3000/components/inspect/marketplace/stripe_overview/default
![Screenshot 2023-09-06 at 7 02 04 PM](https://github.com/zinc-collective/convene/assets/16140873/981614d6-0399-4211-aec1-73e217f68ee2)

# Fix
process of elimination revealed that something about the app/furniture/marketplace/stripe_overview_component.rb is causing the page to 404.

**Comment by zspencer** [comment]
Thank you! I've linked this bug the `Marketplace: Accepting Payments feature: https://github.com/zinc-collective/convene/issues/1576

**Comment by zspencer** [comment]
I've deployed a fix! @KellyAH when you get a chance can you confirm that my fix is great?

**Comment by KellyAH** [comment]
✅ confirmed fixed* on prod. confirmed the payment settings section loads on the "Manage Marketplace" page (`/spaces/<space_name>/rooms/<room_name>/marketplaces/<marketplace_id>/edit`) *if a stripe utility exists. (add it via Sandbox › Configure Space › Add Utility)  

Tested on:
Chrome Version 117.0.5938.88
User: k_ahong@yahoo.com 
Space: "Sandbox"
https://convene.zinc.coop/spaces/sandbox/rooms/cake-cabana/marketplaces/3a73864c-e725-4694-aa3c-97f68d48fd0d/edit

<img width="1566" alt="Screenshot 2023-09-20 at 5 48 43 PM" src="https://github.com/zinc-collective/convene/assets/16140873/a51bd124-9f0e-4417-b55c-36b374661a17">

Found new issue 🐛 https://github.com/zinc-collective/convene/issues/1839
