### ISSUE TITLE
🐞 `Section`: Cannot be removed

### ISSUE THREAD

**Issue by KellyAH** [zinc-collective/convene#1841]
- https://github.com/zinc-collective/convene/issues/1155

Replicated on Prod: https://sandbox.zinc.coop/spaces/sandbox/edit
and Local: `http://localhost:3000/spaces/<space_name>/edit`

Given a space has at least 1 section.
1. Go to any space edit page: `/spaces/<space_name>/edit`
2. Click on any section to go to the section details page `/spaces/<space_name>/rooms/<room-name>/edit`
3. click "Remove Section" button
4. see "You've updated Section '<room-name>' successfully! 🎉"

expected behavior
* Section is deleted and no longer displays on the space edit page

actual behavior
* Section fails to be deleted and still displays on the space edit page

![section fail to be deleted](https://github.com/zinc-collective/convene/assets/16140873/1100c8df-3e7e-448f-a7d1-d03f87cd6bb2)

**Comment by zspencer** [comment]
Oof, this is not ideal. I will nab it 🔜

**Comment by zspencer** [comment]
@KellyAH OK! This is fixed and the fix should be deployed! Can you give it a whirl?

**Comment by KellyAH** [comment]
> @KellyAH OK! This is fixed and the fix should be deployed! Can you give it a whirl?

Confirmed the issues is fixed on prod. TY for fixing it!
Tested on Sandbox space: https://sandbox.zinc.coop/edit w/ user k_ahong@yahoo.com.
✅ can delete a section if it has gizmos or not.
✅ if a section has any gizmos, when clicking  the`Remove Section` button on the section details page, a confirmation pop-up displays.
✅ if no gizmos exist for a section, after clicking `Remove Section` button on the section details page, a confirmation pop-up does not display.
✅ can create new sections and delete them.
