### ISSUE TITLE
New Contributors Onboard Effectively

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/convene#20]
In order to effectively contribute to Convene
As a Contributor
I would like there to be a positioning statement accessible to the world that clearly communicates what problem it is attempting to solve

- [ ] README includes a link to the current milestone + contributor guide?
- [ ] README links to the [Experience Brief](https://docs.google.com/document/d/1cqnQa3NhRxY1gkGekGokeuXKTxS9oMGm3fH1cNasYOo/edit)
- [x] Link to a Persona Document? Maybe [A](https://docs.google.com/spreadsheets/d/1BOBCT0yrgrbCuQFTx_hIQak0FSQjnjjFZVA3YksEv8s/edit#gid=622652343) or [B](https://docs.google.com/document/d/1JwTh2uFTc6pxsXu3njEVKQrv-J5HWExhd1rgT-ravt4/edit#heading=h.s406xaid3udh)

**Comment by zspencer** [comment]
Considering this "done" for now. We need to continuously work towards it, but I'm not sure how to break it down into steps.

**Comment by anaulin** [comment]
As a new contributor, Colombene's Experience Brief was 💯  in this respect, for me. If we're comfortable with sharing that more publicly, we could either link to the Google Doc from the Convene README, or simply move the brief's content into the README.

**Comment by zspencer** [comment]
I like that idea! I think what I'll do is start adding checkboxes to this issue with little things we can do to increase the cohesion of intentionality and purpose throughout the repository.

I'm going to add a few checkboxes that I can think of off-hand real quick-like.
