### ISSUE TITLE
🥔🗜️✨ `Gizmo`: `TextBlock`

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/convene#200]
- https://github.com/zinc-collective/convene/issues/709

A TextBlock allows Residents to place a piece of textual content on the web. Great for things like:

- Lists of Links!
- Describing stuff!
- a Message Of The Day! (Or Month, or Year for those of us who don't update our website ever)

May be able to build off of the [`MarkdownBlock`](https://github.com/zinc-collective/convene/issues/226) or start from scratch!

Ideals:
- WYSIWYG for bolding, italicizing, underlining, etc. 
- Fall-back to straight-up HTML editing mayhaps? (This could be very risky...)

Potential Options:
- [ActionText](https://edgeguides.rubyonrails.org/action_text_overview.html)
- [CKEditor](https://ckeditor.com/)
- [Quill](https://quilljs.com/)
- [TinyMCE](https://www.tiny.cloud/)
- [CKEditor](https://ckeditor.com/)
- [Editor.js](https://editorjs.io/)
- [Draft.js](https://draftjs.org/)

# Andromeda Scenarios:
- [x] Setting the Text of a Textblock
- [ ] Links appear to not work?

## Use Cases
- [ ] 🥔 Member adds Text Block to Room
- [ ] 🥔 Author updates Copy in Text Block
- [ ] 🥔 Reader is presented well-formatted Content
- [ ] 🐞 Links appear not to work due to Turbo
- [ ] 🌱🤔Rename from `Markdown Text Block` to `Text Block`

**Comment by rosschapman** [comment]
🧹  Relegated to [cold storage](https://docs.google.com/spreadsheets/d/1Z_pC21sAKAMyB7xiRAY1--bm1ZKEuFzCzSXfqzHaF08/edit?gid=1828229424#gid=1828229424).
