### ISSUE TITLE
🌫️ `Gizmo`: `Spotlight`

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/convene#201]
## Use Cases
- [ ] `Spotlight` with a Title and Description...
  - [ ] a `Room`
  - [ ] a Movie
    - [ ]  With Captions
   - [ ] an Image
     - [ ] With Alt-Text https://usability.yale.edu/web-accessibility/articles/images
  - [ ] an Arbitrary Website 
    - [ ] With a Image
    - [ ] Prepopulates Content via Open Group Protocol - https://ogp.me
- [ ] As a...
  - [ ] Hero, which is full-width on screen
  - [ ] Card Collection

**Comment by rosschapman** [comment]
🧹  Relegated to [cold storage](https://docs.google.com/spreadsheets/d/1Z_pC21sAKAMyB7xiRAY1--bm1ZKEuFzCzSXfqzHaF08/edit?gid=1828229424#gid=1828229424).
