### ISSUE TITLE
Contributor Experience: Update bin/run script to let people know to open localhost:3000/spaces/system-test

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/convene#206]
Recommended by @KellyAH during today’s mobbing session, it’s not quite clear where to go to start futzing with Convene as a person!

**Comment by user512** [comment]
@KellyAH, @anaulin added some message to guide developer to go to localhost:3000, let us know if this resolve this issue.

**Comment by zspencer** [comment]
`bin/run` now tells folks to open `http://localhost:3000/spaces/system-test/`
