### ISSUE TITLE
🐛  Marketplace: Order link in e-mail notification doesn't work

### ISSUE THREAD

**Issue by anaulin** [zinc-collective/convene#2243]
The link to an order in the order notification that goes to the vendor does not work. It looks like:
http://spaces/piikup/rooms/piikup-bundle/marketplaces/8a729075-9805-43c9-a314-c4cc74abdd1c/orders/e5cbd784-0fe2-4957-9ff5-1377b3f81677

Which is not a valid URL.

**Comment by rosschapman** [comment]
When testing locally the domain segment of the url is there when I click the link. Seems to be rendered correctly in the source as well. 🤔

![image](https://github.com/zinc-collective/convene/assets/5185/7570a101-55cb-457a-ba61-ddf1bf9e1797)

**Comment by rosschapman** [comment]
Considering the ActionMailer [configs](https://github.com/zinc-collective/convene/blob/main/config/initializers/action_mailer.rb#L14-L15) look ok , all I can think of is that the  `APP_ROOT_URL` env var is not getting set on boot.

**Comment by anaulin** [comment]
@rosschapman if your hypothesis about `APP_ROOT_URL` being unset in production is correct, that would mean all link generated by Mailers have this problem. Do the links in other emails have this problem as well? (For example, the one-time password email when you try to log in.)

**Comment by rosschapman** [comment]
Good idea. Let me verify other mailers have the same issue.
