### ISSUE TITLE
🌸 `Space::Header`

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/convene#2379]
- https://github.com/zinc-collective/convene/issues/1154

## Use Cases
- [x] ✨ Showing the https://github.com/zinc-collective/convene/issues/2379
- [x] ✨ Hiding the https://github.com/zinc-collective/convene/issues/2379
- [x] ✨ Customzing the #2379's color

## See Also
- https://github.com/zinc-collective/convene/issues/2266

**Comment by anaulin** [comment]
Looks like all the items in this ticket are completed, so closing this ticket. (Re-open if it needs more work, and add details on what!)
