### ISSUE TITLE
Setup test infrastructure to create test data programmatically in feature tests.

### ISSUE THREAD

**Issue by user512** [zinc-collective/convene#239]
Developer should be able create test data programmatically in feature tests rather than relying only on the seed file.

Ref: https://github.com/zinc-collective/convene/pull/236#issuecomment-822046514

**Comment by zspencer** [comment]
@user512 - Great idea! I'm curious if you have any thoughts on how you would decompose this work or what this may look like?

**Comment by user512** [comment]
No solid thought yet, but I have two different major directions in mind:
1. Create some operatorCreateSpace functions that actually goes thru the operator interface and create spaces, this way we can also make sure the operator interface works as we are building up test.
2. Open up an API interface on Convene that create space, this way the test will be faster, it doesn't test the operator interface, but also open up the possibility on having a public API interface (But I don't think we need it (yet)).

**Comment by zspencer** [comment]
My instincts are we will "want" an API sooner rather than later, and that the `Operators` interface is not something we will be using/maintaining if we can help it; so I'd prefer we went down the path of extending our Spaces controller to support JSON requests for now.

**Comment by user512** [comment]
Great, and good to know. 
Do you have an idea on what's the API for? Might be a useful context when building this out.
