### ISSUE TITLE
Integrate `rubocop-rspec_rails` (or tell rubocop to stop asking us to)

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/convene#2627]
```
Tip: Based on detected gems, the following RuboCop extension libraries might be helpful:
  * rubocop-rspec_rails (https://rubygems.org/gems/rubocop-rspec_rails)

You can opt out of this message by adding the following to your config (see https://docs.rubocop.org/rubocop/extensions.html#extension-suggestions for more options):
  AllCops:
    SuggestExtensions: false
```

Every time we run rubocop it really wants us to add `rubocop-rspec_rails`, maybe we should? Perhaps we shouldn't? Might be there's something in `standard` that does the same job?

Anyway, it would be nice not to see this every time I commit.

Ideally the addition of any additional linting rules does not mutate the source code but does add the new stuff to `rubocop_todo.yml`.

**Comment by Kroch4ka** [comment]
Hello!

I have created a pull request: https://github.com/zinc-collective/convene/pull/2632

**Comment by zspencer** [comment]
Thanks a bunch!
