### ISSUE TITLE
test title

### ISSUE THREAD

**Issue by colombene** [zinc-collective/convene#28]
body

**Comment by zspencer** [comment]
Nice! You can also [add the issue to a project](https://help.github.com/en/github/managing-your-work-on-github/adding-issues-and-pull-requests-to-a-project-board), give it [labels](https://help.github.com/en/github/managing-your-work-on-github/about-labels) so people know what kind of work it may need, or place it in a [milestone](https://help.github.com/en/github/managing-your-work-on-github/tracking-the-progress-of-your-work-with-milestones) so we know which version of Convene we're targeting :).

In the meantime, feel free to close this issue _or_ flesh it issue out more fully with the work you'd like @user512  or I to do for Convene! 

Glad to see you building your confidence with Github :D
