### ISSUE TITLE
Furniture: TextBlock 

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/convene#286]

**Comment by user512** [comment]
If I understand this correctly,  this is to replace/ improve the markdown text block?

**Comment by zspencer** [comment]
@user512 - Yep, basically we want to give people the ability to bold/italicize/underline/hyperlink without knowing an underlying document format. It could be a replacement for the current MarkdownTextBlock (which could be renamed to TextBlock) or it could be it's own and we could deprecate/remove the MarkdownTextBlock.

**Comment by zspencer** [comment]
Merged into https://github.com/zinc-collective/convene/issues/200
