### ISSUE TITLE
Devsign: Sprout a Component Library

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/convene#288]
In order to have a better sense of what user interface elements that are available, it'd be great to have a component library that is built into our application.

Ideally, this would sit in `localhost:3000/components` and show us things like:

1. What does a form look like?
2. What do button(s) look like?
3. What do links look like?

Etc.

**Comment by Wimsy113** [comment]
**View Component As a possible component library solution**

Docs:[View Component Docs]( https://viewcomponent.org/)

Tutorial: [Rails Tutorial | Using View Components to Create Reusable Views in Ruby on Rails](https://youtu.be/oKqJmEAn-X0)

**Summary:**

Today I messed with the View Component Gem  a bit, and followed along to the above linked tutorial. It seems pretty straightforward and simple to use. The tutorial seems to also highlight the migration of existing components over to View Component which I feel is important considering that there's quite a bit to move over. When you generate a new component it creates the html.erb file as well as the ruby files, and the spec (testing) files on creation:

<img width="536" alt="Screen Shot 2021-06-06 at 1 39 40 PM" src="https://user-images.githubusercontent.com/7386887/120934979-afcde100-c6ce-11eb-92a5-b0adf3164ba5.png">

<img width="261" alt="Screen Shot 2021-06-06 at 1 47 36 PM" src="https://user-images.githubusercontent.com/7386887/120935017-d1c76380-c6ce-11eb-9359-2ab40521af85.png">

For the sake of my sanity, it seems pretty easy to pick up, even with me having to shake loose the cobwebs in the part of my brain that has to remember what I'm doing to get ruby stuff to happen. The docs are also well organized and pretty easy to navigate and there's examples for use cases like different states, conditional rendering and collections of components

**Conclusion:**

So far, it looks like it's going to be our best option considering it's made specifically for rails.

**Comment by zspencer** [comment]
Thanks @Wimsy113!!! I really like a lot about how this library works; in particular how it's leaning into the HTML Standard for WebComponents! It looks like it's definitely on the right track! 

Questions I have are:

- What, if any, resources are there available for giving us a "Component Library" interface for visually presenting our components? 
- What would you need from us to feel confident that you can start designing and implementing components using this library within Convene?
- What, if anything, do you see as possible _cons_ of this particular library?

**Comment by zspencer** [comment]
Closing out because it's not moved in a while.
