### ISSUE TITLE
Furniture: Videobridge - Dialing In

### ISSUE THREAD

**Issue by user512** [zinc-collective/convene#43]

**Comment by zspencer** [comment]
How do you feel about the following scenario:

```features/video-workspaces.feature
Feature: Video Workspaces
  In order to communicate effectively while not in the same room
  I want a high quality, reliable, video workspace

  Scenario: Dial in by phone
    Given a Video Workspace is provisioned with the Dial in feature enabled
    When I dial into a Room via Phone
    Then I can hear all the Rooms Participants
    And all the Rooms Participants can hear me
```

From a technical perspective, there are two things we'll need to look into:

1. Setting up our own [SIP](https://en.wikipedia.org/wiki/Session_Initiation_Protocol) server (or finding a vendor who provides affordable SIP)
2. [Installing Jigasi and configuring it to connect to the SIP provider](https://github.com/jitsi/jigasi#incoming-calls) 

![convene-architecture-draft](https://user-images.githubusercontent.com/50284/87229051-eb92e600-c359-11ea-9134-bc9ddd141d2b.PNG)

My gut says that dial-in by phone, while critical, will be a relatively difficult epic to accomplish. I still think it's worth spiking so we can lay out the work that will need to be done to get it working, but I would be hesitant to delay customer development activities until it is completed.

**Comment by user512** [comment]
Agree that this ticket would be a difficult epic and I think we might want to spike this after all other Andromeda tickets are done. I think we can put this back into the Shaping column to indicate we want to do this at a later point, thoughts?
