### ISSUE TITLE
🌫️🗜️✨`Gizmo`: `EmbeddedForm`

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/convene#619]
- https://github.com/zinc-collective/convene/issues/709

Embedded forms allow Space Owners to solicit data using their form-provider of choice. For now, we'll just support Airtable, but at some point it could be nice to support the following Form providers:

- [ ] Airtable
  - [ ] It should work regardless of which share link one uses (i.e. the share, the link to the embed instructions, or the link from the embed)
- [ ] Google Forms
- [ ] TypeForm

For an MVP, it's probably fine to just embed whatever iFrame they tell us to; but it would be super nice if we could actually style the form based upon the Space's intended user interface.

**Comment by rosschapman** [comment]
🧹  Relegated to [cold storage](https://docs.google.com/spreadsheets/d/1Z_pC21sAKAMyB7xiRAY1--bm1ZKEuFzCzSXfqzHaF08/edit?gid=1828229424#gid=1828229424).
