### ISSUE TITLE
🥔🗜️✨ `Gizmo`: `Livestream`

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/convene#632]
- https://github.com/zinc-collective/convene/issues/709

- Embeds a Video from a Livestream Provider, such as Twitch, in #1155

### Use Cases
- [x] Streaming from Twitch
- [x] Streaming from OwnCast

### Watering Hole

> Hoping for a federated, secure platform to share content with our band's fans. VOD, livestreaming, merchandise sales would be ideal, as would free and paid subscriptions.
> - [JB](https://airtable.com/appI2Bdc9NBhWOfTM/tbllaq3XwtiHUfNcF/viwJihQgUU8fCGYvr/recePpmhJRkBdxhbK)

**Comment by rosschapman** [comment]
Appears to be implemented. 🧹  Relegated to [cold storage](https://docs.google.com/spreadsheets/d/1Z_pC21sAKAMyB7xiRAY1--bm1ZKEuFzCzSXfqzHaF08/edit?gid=1828229424#gid=1828229424).
