### ISSUE TITLE
🌫️ `Spaces`: Purchasing a Space

### ISSUE THREAD

**Issue by user512** [zinc-collective/convene#8]
## Scenarios:

- [ ] Guest Purchases a Space
  - [ ] Guest submits Down Payment  (See: #186)
  - [ ] Guest Submits Form with Space Details
       - [ ] Space Owner may Embed Form (See: #619)
  - [ ] Operators are emailed when a Space Request is submitted

- [ ] Resident purchases a Space
- [ ] Utilities: Stripe (TODO: Create a Ticket for Stripe Utility)
  - [ ] Stripe Hookup exposes products, plans, and prices 
- [ ] Furniture: Order Form (TODO: Create a Ticket for an Order Form furniture)

**Comment by zspencer** [comment]
This is distinct from #9 in that we can be successful with this purely by allowing our creators to create an always-on video room.

This will build on top of the work we're doing in https://github.com/zinc-collective/convene/issues/2 to automate the provisioning of a Jitsi instance by creating affordances for Organizers to create a video room they can use at any time of day.

#8 is  more _expensive_ than #9 for Organizers, as each Video Room is an independent Jitsi server. AWS's pricing for a T3 micro is about $15/mo, which means we'd need to charge $45/mo; and we don't know how many folks can "fit" in that room.

But it also allows us to package up the work we're doing to automate provisioning and deploying of Jitsi instance(s) in #2 into a Minimal (potentially) Viable Product without adding the scope of scheduling.

I'm considering a few scenarios, and would appreciate thoughts from @zinc-collective/convene-maintainers about which of these (or others!) would be reasonable next steps for this epic.

```features/permanent-video-rooms.feature
Scenario: Organizer creates a tiny paid video room 
  Given an Organizer creates a tiny Video Room
  When Convene programaticaly provisions the tiny Video Room
  Then the Organizer can use the Video Room at any time
```

This scenario is slightly different, in that we assume there is no automation beyond the gathering of the Organizer's payment information and contact information.

The work of provisioning the Video Room is performed manually by an Operator (@user512 or I), and we would replace this scenario with an automated one once we've confirmed the market actually is willing to pay for private, secure video rooms.

```features/permanent-video-rooms.feature
Scenario: Organizer requests we provision a tiny paid video room
  Given an Organizer requests a tiny Video Room
  When an Operator provisions the Video Room
  Then the Organizer can use the Video Room at any time
```

Thoughts @zinc-collective/convene-maintainers?

**Comment by maximegalon5** [comment]
Given the conversations we're having I think Scenario: Organizer requests we provision a tiny paid video room.

**Comment by zspencer** [comment]
Sounds great! I've updated the feature definition with that scenario, and added some check-boxes that will tell us when we can close this issue out.

**Comment by maximegalon5** [comment]
I've put created a mockup and some app flow here ([GD](https://docs.google.com/presentation/d/1j2XQ5jR4JrSKTfzufi-7joc6nxT0NMAkZ0UlVbiIRyk/edit?usp=sharing))

**Comment by zspencer** [comment]
Once https://github.com/zinc-collective/www.zinc.coop/pull/48 is merged, I think we can check off the first checkbox! We'll still have a ways to go for getting people _into_ the system; but at least we'll have a way for potential clients to _ask_ to use convene!

**Comment by zspencer** [comment]
I've scoped this down a bit in the hopes that we can bring it to completion. In particular, I wanted to:

1. Remove the constraint that we have to have sold the product in order to call this "done"
2. Make it so when someone buys Convene a Workspace is created in convene.zinc.coop.
3. Make a requirement that the customer team and operators are notified when someone buys a Workspace (so we can actually get their video going)

**Comment by rosschapman** [comment]
🧹  Relegated to [cold storage](https://docs.google.com/spreadsheets/d/1Z_pC21sAKAMyB7xiRAY1--bm1ZKEuFzCzSXfqzHaF08/edit?gid=1828229424#gid=1828229424).
