### ISSUE TITLE
🌫️✨ `Space`: Download as an App on Mobile App Stores

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/convene#833]
- https://github.com/zinc-collective/convene/issues/1154

It would be cool if each Space could be packaged as an App for distribution on the iOS or Android App Store(s)

## Bounties:
- $109.52 from https://github.com/zinc-collective/convene/issues/832

## Use Cases

- [ ] `Space` is Installable via iOS App Store
- [ ] `Space` is Installable via Google Play Store

**Comment by zspencer** [comment]
- $109.52 Bounty offered by https://github.com/zinc-collective/convene/issues/832 

Invoice: https://app.qbo.intuit.com/app/invoice?txnId=588

**Comment by rosschapman** [comment]
🧹  Relegated to [cold storage](https://docs.google.com/spreadsheets/d/1Z_pC21sAKAMyB7xiRAY1--bm1ZKEuFzCzSXfqzHaF08/edit?gid=1828229424#gid=1828229424).
