### ISSUE TITLE
🌫️🗜️✨ `Gizmo`: `ContactForm`

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/convene#847]
- https://github.com/zinc-collective/convene/issues/709

### Fauxsonas
- Contactor - Wants to contact the Organization. Can be unauthenticated, a Neighbor, or a Resident of the Space.
- Recipient - Wants to receive messages in a manner that fits their schedule and priorities.
- Suspicious User - Wants to spam the Organization with gibberish.

### Supplants
_Lead Form_ allows organizations to replace subscriptions to the following capital-oriented products and services by providing Guests affordances to contact the owners of a Space.

- HelpScout
- ZenDesk
- HubSpot
- Squarespace
- ???

### Client Owners
- MomentPark
- Cohere (Potential)
- ZTN (Potential)
- Zee Spencer (Potential)

### Use Cases
- [ ] https://github.com/zinc-collective/convene/issues/851
- [ ] Recipient may choose to receive future Messages 
  - [ ] Recipient may pick which email address to receive Messages from their set of confirmed Contact Methods 
- [ ] Recipient may choose not to receive future Messages 
- [ ] Contactor may send Recipients a Message via Contact Form
  - [ ] Contactor receives a Confirmation Email that their Message has been received
  - [ ] Recipient receives new Messages via Email
- [ ] Recipient may responds to Messages via Email
  - [ ] Contactor receives response to Messages via Email
- [ ] Contactor may respond to Messages via Email
- [ ] Suspicious User may not send a Message via Contact Form

**Comment by rosschapman** [comment]
🧹  Relegated to [cold storage](https://docs.google.com/spreadsheets/d/1Z_pC21sAKAMyB7xiRAY1--bm1ZKEuFzCzSXfqzHaF08/edit?gid=1828229424#gid=1828229424).
