### ISSUE TITLE
✨ `ContactForm`: Submitting from a Static Site

### ISSUE THREAD

**Issue by anaulin** [zinc-collective/convene#851]
- https://github.com/zinc-collective/convene/issues/847

## Use Cases
- [ ] `ContactForm`: Expose HTML to embed the `ContactForm` in a Static site
- [ ] `ContactForm`: Add domain names that are allowed to submit the `ContactForm`

## Engineering Notes

Zee implemented this in a distinct web-app at: https://github.com/zinc-collective/support; it may be useful to read if you run into weird HTTP stuff.

**Comment by zspencer** [comment]
Yea! This would be lovely! I've added it as the top checkbox for the broader Contact Form furniture issue I sprouted to encapsulate the full user experience: https://github.com/zinc-collective/convene/issues/847
