### ISSUE TITLE
🌫️🗜️✨`Gizmo`: `RecipeBox`

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/convene#881]
- https://github.com/zinc-collective/convene/issues/709

Save, ReMix, and Track Recipes!

Previously: https://github.com/zinc-collective/recipe-box

**Comment by rosschapman** [comment]
🧹  Relegated to [cold storage](https://docs.google.com/spreadsheets/d/1Z_pC21sAKAMyB7xiRAY1--bm1ZKEuFzCzSXfqzHaF08/edit?gid=1828229424#gid=1828229424).
