### ISSUE TITLE
`Lead`: Artisans.coop

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/convene#888]
Artisans.coop is exploring building out an artisan-owned Etsy alternative. They are doing incredibly well on the customer + community development side of things, but may not have significant technology bandwidth.

Interested in:
-  https://github.com/zinc-collective/convene/issues/831.

**Comment by zspencer** [comment]
Artisan's Cooperative's January 2023 Open House has several great insights into what they're hoping for from a technology solution: https://www.youtube.com/watch?v=cfh8JTCNIDs

**Comment by zspencer** [comment]
They also released an excellen summary of their marketplace priorities: https://artisans.coop/blog/marketplace-priorities-poll-results/

**Comment by rosschapman** [comment]
🧹  Relegated to [cold storage](https://docs.google.com/spreadsheets/d/1Z_pC21sAKAMyB7xiRAY1--bm1ZKEuFzCzSXfqzHaF08/edit?gid=1828229424#gid=1828229424).
