### ISSUE TITLE
`Lead`: Indie Sellers Guild

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/convene#889]
Kristi, interim president of Indie Sellers Guild [reached out](https://airtable.com/appI2Bdc9NBhWOfTM/tbllaq3XwtiHUfNcF/viwJihQgUU8fCGYvr/rec2gcBi4nnULY4MF?blocks=hide) after reading a thread I wrote in the artisans.coop discord.

Interested in:
- https://github.com/zinc-collective/convene/issues/831

**Comment by rosschapman** [comment]
🧹  Relegated to [cold storage](https://docs.google.com/spreadsheets/d/1Z_pC21sAKAMyB7xiRAY1--bm1ZKEuFzCzSXfqzHaF08/edit?gid=1828229424#gid=1828229424).
