### ISSUE TITLE
🥔✨ `Neighborhood`: `Operator` First Run Experience

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/convene#890]
There's a number of pain points around setting up Convene for new contributors. This is a catch-all for tracking the pain-points and polish for setting up a new neighborhood as a Contributor.

- [x] https://github.com/zinc-collective/convene/issues/755

**Comment by rosschapman** [comment]
🧹  Relegated to [cold storage](https://docs.google.com/spreadsheets/d/1Z_pC21sAKAMyB7xiRAY1--bm1ZKEuFzCzSXfqzHaF08/edit?gid=1828229424#gid=1828229424).
