### ISSUE TITLE
🌫️ `Neighborhood`: Hosted `Utilities`

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/convene#891]
Utilities _may_ be deployed into a Convene Neighborhood. For example a Jitsi Meet installation to the Neighborhood's server Culster.

At present, we have been using [Ansible](https://www.ansible.com/), [Packer](https://www.packer.io/), and [Terraform](https://www.terraform.io/) to for deployment; but that is quite heavy weight. It may be prudent for us to leverage [Abra](https://git.coopcloud.tech/coop-cloud/abra) by [CoOpCloud](https://coopcloud.tech/) or a similar technology to streamline provisioning additional Neighborhood-hosted Utilities

Potential Hosted Utilities:

- `OwnCast`
- `BitKeeper`
- ???

**Comment by rosschapman** [comment]
🧹  Relegated to [cold storage](https://docs.google.com/spreadsheets/d/1Z_pC21sAKAMyB7xiRAY1--bm1ZKEuFzCzSXfqzHaF08/edit?gid=1828229424#gid=1828229424).
