### ISSUE TITLE
🌫️🗜️✨ `Gizmo`: `FediProxy`

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/convene#973]
Publish your activity-pub feeds on a domain you control!

### Watering Hole
> Is there a service that will host a single Mastodon account for me (not an entire instance) but let me alias it to my own domain? I don't want to run an instance, but I would like to control my address/handle. - [@anildash](https://social.coop/@anildash@mastodon.cloud/109463814330222661)

> I dream of a blocklist tool that works across multiple ActivityPub implementations. Like... if I could share between my Mastodon, Pixelfed, and BookWyrm instances :blobcatmaths: [#MastoAdmin](https://social.coop/tags/MastoAdmin) - [@josh@josh.tel](https://social.coop/@josh@josh.tel/109464811427481018) 

> Lots of useful functionality in a low-feature, lightweight store-and-forward service that's less like a full-blown social site and more like an old-school SMTP+IMAP server for email - [@lmorchard@hackers.town](https://hackers.town/@lmorchard/109677440839541341)

> I'm curious -- has anyone written a twitter-algorithm-style app for mastodon? Just something that would show you a more curated subset of your existing timeline. ("here are 20 popular things from today", "3 people you follow boosted this toot", "here is something that got 50 boosts that one of your followers boosted", etc.)
> 
> (please do not tell me about hashtags :)) - [@bork@social.jvns.ca](https://social.jvns.ca/@b0rk/109718243620570350)

### Super Powers
- Aggregate your posts from multiple ActivityPub service providers (BookWyrm, Pixelfed, Hometown, Mastodon, PeerTube, etc.) and publish them as a feed on your custom domain!  All without needing to write a line of code!
- Leverage the wisdom of community and apply moderation rules from your upstream providers
- Curate an always up-to-date living autobiography from your activity and posts from around the web.

### FauxSonas
- Publisher - Author + Distributor of content
- Followers - Receivers of the Publisher's content. 
- Respondents - Anyone who remixes, reply to, or reference the Publisher's content

_Wish this was further along? Consider sponsoring our [Zinc Community Fund](https://opencollective.com/zinc-community), which we use to cover our operating costs and pay contributors!_

### MVP
 - [ ]  Aggregate Your Posts!
   - [ ] 🌱 Publisher may Place FediProxy in
     - [ ] Community Space 
     - [ ] Commercial Space
   - [ ] 🌱 Publisher may set Handle on the Space's Domain (i.e. @zee@zeespencer.com)
    - [ ] Follower may Follow the FediProxy
      - [ ] 🌱 Via their preferred ActivityPub Client
      - [ ] Via email
      - [ ] Via text
  - [ ] 🌱 Publisher may Follow an ActivityPub Feed via the FediProxy  (i.e. Collect all posts from @zee@social.coop)
  - [ ] 🌱 Publisher may Follow an Authenticated ActivityPub Feed via the FediProxy  (i.e. Sign in as @zee@social.coop)
  - [ ] 🌱 Publisher may Boost Posts from...:
    - [ ]  🌱 an Authenticated ActivityPub Feed
    - [ ]  🌱 an ActivityPub Feed
  - [ ] 🌱 Publisher may Re-Publish Posts from an Authenticated Feed 
         (Re-published posts are distributed to Followers using the FediProxies handle)
  - [ ] 🌱 Publisher may see Responses
    - [ ] 🌱 Publisher may React or Respond to Responses from an Authenticated Feed
- [ ] 🌱 Publisher may apply Moderation decisions from Authenticated Mastodon/HomeTown Accounts
  - [ ] ... 🌱 Block Publication to Domains 
     - [ ] ... 🌱 Automatically
  - [ ] ... 🌱 Block Publication to Followers
      - [ ] ... 🌱 Automatically
  - [ ] ... Refuse Responses from Domains 
  - [ ] ... Refuse Responses from Respondents

_Wish this was further along? Consider sponsoring our [Zinc Community Fund](https://opencollective.com/zinc-community), which we use to cover our operating costs and pay contributors!_

**Comment by anaulin** [comment]
Somewhat related, there is the Microsub standard, and "aggregator" implementations like https://aperture.p3k.io/

**Comment by zspencer** [comment]
I dig it! Other protocols like RSS, etc seem like a prudent call; and exposing the output in a format that's readable by existing apps also seems prudent.

**Comment by rosschapman** [comment]
🧹  Relegated to [cold storage](https://docs.google.com/spreadsheets/d/1Z_pC21sAKAMyB7xiRAY1--bm1ZKEuFzCzSXfqzHaF08/edit?gid=1828229424#gid=1828229424).
