### ISSUE TITLE
🌫️🗜️✨ `Gizmo`: `B-Corp Certification Wizard`

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/convene#990]
Streamline the logistical and emotional labor of becoming B-Corp certified

#### Ambassador - _Facilitates effective communication and collaboration between Certifier and Applicant_

_Wish this was further along? Consider sponsoring our [Zinc Community Fund](https://opencollective.com/zinc-community), which we use to cover our operating costs and pay contributors!_

### Client Owners:
- https://github.com/zinc-collective/convene/issues/988

### Use Cases

  
_Wish this was further along? Consider sponsoring our [Zinc Community Fund](https://opencollective.com/zinc-community), which we use to cover our operating costs and pay contributors!_

**Comment by rosschapman** [comment]
🧹  Relegated to [cold storage](https://docs.google.com/spreadsheets/d/1Z_pC21sAKAMyB7xiRAY1--bm1ZKEuFzCzSXfqzHaF08/edit?gid=1828229424#gid=1828229424).
